### ISSUE TITLE
Any Extension....

### ISSUE THREAD

**Issue by mady143** [aahmad4/Resume-Scanner#2]
Hi @aahmad4 ,
Thank you for our reply and explanation and i had a small doubt i was very efficient running our code is their any chance of extending in code and any chance of getting and extracting of experience from the resume 
and Actually i had given m personal resume and compared to our code(jobdescribtion.docx file) i got an 41% matching score but i was in a confused state that is good enough or not and later i add some information/technologies which is in my resume then i got 44% matching score then also a little bit confusion among the score and also their is a small change in uploading with docx and pdf files i am getting different different % in different files like (docx and pdf) files...
can you explain it clearly why and whats happening...

Thanks and Regards,
Manikantha Sekhar...

**Comment by aahmad4** [comment]
Hi @mady143,
Right now I have coded the program to only take docx files or txt files, but later I can definitely change this to accept pdf documents. I would say that a similarity score of around 40% and higher would be considered substantially close in the essence of matching the resume to a job description. I appreciate your interest in the program and please let me know if you have any other questions.
Sincerely,
Ali Ahmad
