### ISSUE TITLE
possibilities...!! 

### ISSUE THREAD

**Issue by mady143** [aahmad4/Resume-Scanner#3]
Hi @aahmad4 ,

Actually I am very much happy for your responses for my issues or any related questions and i had a small doubt about the result or %  which we are getting in the final execution is it possible to get the 80% to 90% job matching to the given resume  for this how the cosine similarity works and vectorisation works can you explain....

Thanks and Regards,
Manikantha Sekhar...

**Comment by aahmad4** [comment]
Hey @mady143 ,
Yes, it's very possible to get higher scores with this metric. I updated my README file to include all the information on how this works. 

Best Regards,
Ali Ahmad
